"""dodanie constraint w CartItem

Revision ID: 8cb0132ceada
Revises: 2281ba8c9c3c
Create Date: 2025-01-11 11:53:30.971318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb0132ceada'
down_revision = '2281ba8c9c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_cart_part', ['cart_id', 'part_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint('uix_cart_part', type_='unique')

    # ### end Alembic commands ###
