"""Part and Comment tables

Revision ID: 9dd5d2869091
Revises: 414390e7c57a
Create Date: 2024-12-12 18:54:06.742745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd5d2869091'
down_revision = '414390e7c57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_part_description'), ['description'], unique=True)
        batch_op.create_index(batch_op.f('ix_part_part_name'), ['part_name'], unique=True)

    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=360), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_body'), ['body'], unique=True)
        batch_op.create_index(batch_op.f('ix_comment_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_part_id'))
        batch_op.drop_index(batch_op.f('ix_comment_body'))

    op.drop_table('comment')
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_part_name'))
        batch_op.drop_index(batch_op.f('ix_part_description'))

    op.drop_table('part')
    # ### end Alembic commands ###
