"""empty message

Revision ID: b2d19b04ec8e
Revises: fd008dc543eb
Create Date: 2025-01-24 19:34:34.482681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d19b04ec8e'
down_revision = 'fd008dc543eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Dodaj kolumnę jako NULL
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(), nullable=True))

    # 2. Ustaw wartości dla istniejących rekordów (tutaj ustawiamy 'unknown' dla wszystkich)
    op.execute("UPDATE orders SET payment_method = 'unknown'")

    # 3. Zmień kolumnę na NOT NULL
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('payment_method', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
