"""metoda dostawy

Revision ID: b69123c87867
Revises: b2d19b04ec8e
Create Date: 2025-01-24 20:58:11.857839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69123c87867'
down_revision = 'b2d19b04ec8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_method', sa.String(), nullable=True)) # Tymczasowo NULL

    # Ustaw wartości dla istniejących rekordów (np. 'unknown')
    op.execute("UPDATE orders SET delivery_method = 'unknown'")

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('delivery_method', nullable=False) # Zmień na NOT NULL

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_method')

    # ### end Alembic commands ###
