"""usuniecie constraint w CartItem

Revision ID: d8d8d08be98c
Revises: 8cb0132ceada
Create Date: 2025-01-11 12:19:34.343305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d8d08be98c'
down_revision = '8cb0132ceada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint('uix_cart_part', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_cart_part', ['cart_id', 'part_id'])

    # ### end Alembic commands ###
