"""dodanie ceny

Revision ID: fd008dc543eb
Revises: 0839fb3b69de
Create Date: 2025-01-11 17:14:32.480822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd008dc543eb'
down_revision = '0839fb3b69de'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DELETE FROM part")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.create_index(batch_op.f('ix_part_group'), ['group'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_group'))
        batch_op.drop_column('price')
        batch_op.drop_column('group')

    # ### end Alembic commands ###
